# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fde0bcde9a910073daf37e04d8e199ba46e1c41aef70f8d1cde5574e68a9422b16a47e32f82a9209219f1e742da48ca85d8c62ba6604ba6e27343808e294e4c3

test:
  secret_key_base: 92646867e715034814a36b7e1394a178cddad5cb01763c88911154ddca9d4c2d9eac61e3f04e7db13d3ea21cc10786055bb23a7d036bb58c4685b86b23b7a74b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
